### ISSUE TITLE
Issues about the loss function

### ISSUE THREAD

**Issue by JessieLi-RS** [mkhorr/supergluetraining#1]
Dear author,

Thank you for your contribution. However, I noticed that you have changed the original negative log-likelihood loss to another loss function. May I ask the reason??

Best,
Jessie

**Comment by mkhorr** [comment]
Hello,

Apologies for the code’s readability, but the loss function used is still negative log likelihood. The inputs to loss_fn are the row and column indices of the P matrix (in log space) where the corresponding values are the summed terms of the loss. The terms are then weighted based on the author’s suggestion [here](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/31#issuecomment-684986482).
